channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=25.1.1
- pip:
  - mlflow==2.22.1
  - cloudpickle==3.1.1
  - numpy==2.0.0
  - pandas==2.3.1
  - scikit-learn==1.5.0
  - scipy==1.13.1
  - xgboost==3.0.2
name: mlflow-env
