name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: gcr.io/plucky-haven-463121-j1/intrusion-api
  TAG: latest

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --deploy --system

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --system
          pip install pre-commit
      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --system
      - name: Run tests
        run: pytest tests/ --maxfail=1 --disable-warnings -q

  build-and-push:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '414.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: plucky-haven-463121-j1
      - name: Build and push Docker image to GCR
        run: make gcloud-build
